server:
  port: 8082

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://39.108.62.171:3306/auth-example-20210924?useSSL=false
    username: root
    password: 123456

  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 39.108.62.171
    port: 5672
    username: test
    password: test098
    virtual-host: /test
    # 确认消息发送到交换机上 --开启回调
    publisher-confirm-type: correlated
    # 确认消息已发送到队列 --开启回调
    publisher-returns: true


