server:
  port: 8083

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 39.108.62.171
    port: 5672
    username: test
    password: test098
    virtual-host: /test
    listener:
      simple:
        # prefetch越大消费能力越强
        prefetch: 3
        #自动签收auto  手动 manual  默认自动签收
        acknowledge-mode: auto
        retry:
          # 开启重试机制
          enabled: true
          # 重试次数
          max-attempts: 5
          # 最大间隔时间
          max-interval: 20000
          # 重试间隔时间（单位毫秒）
          initial-interval: 1000
          #乘子  重试间隔*乘子得出下次重试间隔  2s  4s  8s  16s  此处32s>20s  走20s
          multiplier: 2
          # 重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
        default-requeue-rejected: false

