version: '2'
services:
  flowable-ui:
    image: flowable/flowable-ui:6.6.0
    container_name: flowable-ui
    ports:
      - "9012:8088"
    restart: always
    environment:
      - SERVER_PORT=8088
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://p2wan.fun:3306/flowable?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    volumes:
      - ./mysql-connector-java-5.1.49.jar:/app/WEB-INF/lib/mysql-connector-java-5.1.49.jar

# 启动 docker-compose up -d
# 暂停 docker-compose down
# 访问 http://localhost:9012/flowable-ui/
